name: Update Last 10 Tracks

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours (adjust as needed)
  push:
    branches:
      - main # or your default branch

jobs:
  update-tracks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script to generate markdown file
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        run: |
          python generate_markdown.py

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add content/music.md
          git commit -m "music.md"

      # Ensure changes are pushed back before deployment 
      - name : Push changes back to repository
        uses : ad-m/github-push-action@v0.6.0
        with :
          github_token : ${{ secrets.GITHUB_TOKEN }}
